debug: false
baseURL: http://localhost:3000
listenAddr : ":3000" 
staticDir: "./static"
templateDir: "./templates"
allowOrigins: 
 - http://localhost:8080

session:
  sessionMaxAge: "24h"
  cookieName: "sid"
  cookieSecure: false
  cookieHttpOnly: true

redis:
  url: redis://default:123456@localhost:6379/0
  poolSize: 20
  clusterMode: true

mysql:
  dsn: user:password@tcp(localhost:3306)/kauth?charset=utf8mb4&parseTime=True&loc=Local
  maxIdleConns: 10
  maxOpenConns: 10
  connMaxIdleTime: 10
  connMaxLifetime: 10

authProviders: 
  oauth:
    google:
      clientId: xxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com
      clientSecret: xxxxxx-xxxxxxxxxxxxxxxxxxxxxxxxxxxx
    discord:
      clientId: xxxxxxx
      clientSecret: xxxxxx

mail:
  backend: smtp
  smtp:
    host: smtp.example.com
    port: 587
    username: admin@example.com
    password: password
    from: noreply@example.com
    tls: true
    certFile: "./cert.pem"
    keyFile: "./keypem"
    caFile: "./ca.pem"

captcha:
  provider: turnstile
  turnstile:
    siteKey: "YOUR_TURNSTILE_SITE_KEY"
    secretKey: "YOUR_TURNSTILE_SECRET_KEY"
