apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "kauth.fullname" . }}
  {{- with .Values.deployment.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
  {{- include "kauth.labels" . | nindent 4 -}}
  {{- with .Values.deployment.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ default 1 .Values.deployment.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kauth.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    {{- with .Values.rollingUpdate }}
    rollingUpdate:
      {{- toYaml . | nindent 8 }}
    {{- end }}
  minReadySeconds: {{ .Values.deployment.minReadySeconds | default 5 }}
  template: {{ template "kauth.podTemplate" . }}
