# Default values for mcrunner
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: registry.example.com/kauth
  # This sets the pull policy for images.
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

# -- The service account the pods will use to interact with the Kubernetes API
serviceAccount:  # @schema additionalProperties: false
  # If set, an existing service account is used
  # If not set, a service account is created automatically using the fullname template
  name: ""

# Tolerations allow the scheduler to schedule pods with matching taints.
tolerations: []

# https://kubernetes.io/docs/tasks/configure-pod-container/assign-pods-nodes-using-node-affinity/
affinity: {}
  # nodeAffinity:
  #   required:
  #     nodeSelectorTerms:
  #     - matchExpressions:
  #       - key: node-role.kubernetes.io/control-plane
  #         operator: Exists

# nodeSelector is the simplest recommended form of node selection constraint.
nodeSelector: {}
  # kubernetes.io/hostname: hcm01

# Additional volumes on the output Deployment definition.
additionalVolumes: []

deployment:
  kind: Deployment
  # This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
  replicas: 3
  # This is for setting Kubernetes Annotations to a Pod.
  # For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
  podAnnotations: {}
  # This is for setting Kubernetes Labels to a Pod.
  # For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
  podLabels: {}
  # -- Security context to be added to spire agent pods.
  # SecurityContext holds pod-level security attributes and common container settings.
  # ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
  podSecurityContext: {}
    # runAsGroup: 65532
    # runAsNonRoot: true
    # runAsUser: 65532
  # Additional volumeMounts on the output Deployment definition.
  additionalVolumeMounts: []
  envFrom: []
  # - configMapRef:
  #   name: special-config
  initContainers: []

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: ClusterIP
  # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 3000

# This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  requests:
    cpu: "100m"
    memory: 64Mi
  limits:
    cpu: "1.0"
    memory: 256Mi

# This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
livenessProbe:
  enabled: false
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1

readinessProbe:
  enabled: false
  initialDelaySeconds: 15
  periodSeconds: 15
  timeoutSeconds: 5
  failureThreshold: 1
  successThreshold: 1

config: |
  debug: false
  siteName: Example App
  baseURL: https://auth.example.com
  listenAddr : ":3000" 
  staticDir: "./static"
  allowOrigins: [] 
  session:
    sessionMaxAge: "24h"
    cookieName: "sid"
    cookieSecure: false
    cookieHttpOnly: true
  redis:
    url: redis://default:123456@localhost:6379/0
    poolSize: 20
    clusterMode: true
  mysql:
    dsn: user:password@tcp(localhost:3306)/kauth?charset=utf8mb4&parseTime=True&loc=Local
    maxIdleConns: 10
    maxOpenConns: 10
    connMaxIdleTime: 10
    connMaxLifetime: 10
  authProviders: 
    oauth:
      google:
        clientId: xxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com
        clientSecret: xxxxxx-xxxxxxxxxxxxxxxxxxxxxxxxxxxx
  mail:
    from: "Example App <noreply@example.com>"
    backend: smtp
    smtp:
      host: smtp.example.com
      port: 587
      username: admin@example.com
      password: password
      from: noreply@example.com
      tls: true
      certFile: "/app/certs/cert.pem"
      keyFile: "/app/certs/key.pem"
      caFile: "/app/certs/ca.pem"
  captcha:
    provider: turnstile
    turnstile:
      siteKey: "YOUR_TURNSTILE_SITE_KEY"
      secretKey: "YOUR_TURNSTILE_SECRET_KEY"
